add Raven-RWKV-7B example
lhenault/simpleAI pull request #3
Opened 2023-03-30 13:10 UTC by Nintorac

2023-03-30 16:34 UTC, lhenault requested changes
Hey thanks a lot for submitting this one! I've been wanting to try RWKV model so it's great!

I think it's a good work but it would benefit from a bit of cleanup and polishing, just to make sure it's easy for anyone who wants to use it.

2023-03-30 16:34 UTC, lhenault commented on examples/Raven-RWKV-7B/model.py
> +    def __post_init__(self):
I think we can simply remove the `__post_init__` here

2023-03-30 16:34 UTC, lhenault commented on examples/Raven-RWKV-7B/model.py
> +        for response in output:
Can't we simply return output here?

2023-03-30 16:34 UTC, lhenault commented on examples/Raven-RWKV-7B/README.md
The README should be updated, as it still references OpenChatKit rather than [RWKV repo](https://github.com/BlinkDL/RWKV-LM)

2023-03-30 16:34 UTC, lhenault commented on examples/Raven-RWKV-7B/get_models.py
> +    get_model()
Can maybe the tokenizer JSON file be fetched there instead of being in the repo? File itself isn't massive but I'd rather do this (can also be useful if updated later by owners).

2023-03-30 16:34 UTC, lhenault commented on examples/Raven-RWKV-7B/model.py
> +        return response
Missing newline

2023-03-31 08:27 UTC, Nintorac commented on examples/Raven-RWKV-7B/get_models.py
> +    get_model()
:(  goodbye 100k LOC commit aha

2023-03-31 08:27 UTC, Nintorac commented
Nice, thanks for the review :) that should all be sorted now

2023-03-31 12:23 UTC, lhenault commented
Looks good, thanks for the changes. I'd like to test it and perhaps add these `chat` / `instruct` interfaces discussed in #4 before merging, but solid work!

2023-04-04 13:59 UTC, lhenault commented
There was an issue in the `README` fixed with #8, and is still in this one.

2023-04-05 12:09 UTC, Nintorac commented
had a bit more of an end to end test today, this includes a few other fixes to tie it all together

and CI :) tested and it fails on [c60ef5e](https://github.com/lhenault/simpleAI/pull/3/commits/c60ef5edffda2bb5d8b6ebe382c87fabc78bedf6)

2023-04-05 12:36 UTC, lhenault commented on src/simple_ai/server.py
> +    llm = get_model(model_id=body.model, task="chat")
Ah that's weird I remember spotting this one and fixing it, I don't know why it's still there. My bad.

2023-04-05 12:54 UTC, lhenault commented
> and CI :) tested and it fails on [c60ef5e](https://github.com/lhenault/simpleAI/pull/3/commits/c60ef5edffda2bb5d8b6ebe382c87fabc78bedf6)

Is the issue related to the code or to an incorrect config file ? I ran some tests without issues with the following config:

```
[test-chat]
    [test-chat.metadata]
        owned_by    = 'Me'
        permission  = []
        description = ''
    [test-chat.network]
        type = 'gRPC'
        url = 'localhost:50051'
```

I now realize the `type` field isn't properly documented in the `README`, yet is present in the latest template, perhaps causing the issue with [c60ef5e](https://github.com/lhenault/simpleAI/pull/3/commits/c60ef5edffda2bb5d8b6ebe382c87fabc78bedf6).

2023-04-05 13:11 UTC, Nintorac commented
na, the precommit jobs just runs ruff and black and fails if they detect issues

2023-04-05 13:17 UTC, lhenault commented on src/simple_ai/utils.py
>                  "role": "assistant",
That one can be deleted thanks to the fix.

2023-04-05 13:17 UTC, lhenault commented on src/simple_ai/models.py
> -        model_interface = model_interface.get("type", None)
I'm not sure the changes there are for the better if that's driven by a config file issue. 

I think it might be bringing more clarity to expect from the user to explicit which kind of interface we're using (so far it's only gRPC but I would like to add at least REST later on). Maybe useful to have some default settings to allow leaner configuration though.

2023-04-05 13:17 UTC, lhenault commented on pyproject.toml
> +name = "simple_ai"
Actually the project is `simple_ai_server` [on Pypi ](https://pypi.org/project/simple-ai-server/) as `simple_ai` was already taken.

2023-04-05 13:37 UTC, Nintorac commented on src/simple_ai/models.py
> -        model_interface = model_interface.get("type", None)
```

def select_model_type(model_interface: str, task: str = "complete"):
    if model_interface == "gRPC":
        if task == "embed":
            return RpcEmbeddingLanguageModel
        if task == "chat":
            return RpcChatLanguageModel
        return RpcCompletionLanguageModel
    return RpcCompletionLanguageModel


def get_model(model_id: str, metadata: dict = MODELS_ZOO, task: str = "complete"):
    if model_id in metadata.keys():
        model_interface = metadata.get(model_id).get("network", dict())
        model_url = model_interface.get("url", None)
        model_interface = model_interface.get("type", "gRPC")
        return select_model_type(model_interface, task)(name=model_id, url=model_url)
    else:
        return None
```
the default is set here,  `model_interface = model_interface.get("type", "gRPC")`. the explicit `None` makes it though into the function doesn't get replaced. should maybe be `model_type = ` too?

2023-04-05 13:37 UTC, Nintorac commented on pyproject.toml
> +name = "simple_ai"
Ah I wondered about that, I thought I had done it for some reason, the examples will need updating

2023-04-05 13:37 UTC, Nintorac commented on src/simple_ai/utils.py
>                  "role": "assistant",
Still needed, I think? the grpc endpoint returns a list of Messages which are `role, content`

2023-04-05 14:05 UTC, lhenault commented on src/simple_ai/utils.py
>                  "role": "assistant",
I've been running out of coffee this morning so I may not be the sharpest knife in the kitchen today, but isn't it the purpose of the change below (L53)? Role is only declared in `message` in [OpenAI API](https://platform.openai.com/docs/api-reference/chat).

2023-04-05 15:00 UTC, lhenault commented on src/simple_ai/models.py
> -        model_interface = model_interface.get("type", None)
The `None` / `"gRPC"` is the default value if the `"type"` field isn't present in `models.toml` for the given model. But as long as it is there and using a valid value (`"gRPC"`), it works as intended in the original version. If everything is configured properly, neither the `None` or `"gRPC"` shall be accessed. 

I reckon that your change works too, I'm just not convinced it's necesary right now, but I might be missing your point. :)
Tbh that might be a change for the better to have default behaviours for missing fields, but that might be a discussion to have later outside the scope of this PR.

2023-04-05 15:08 UTC, lhenault commented on pyproject.toml
> +name = "simple_ai"
The examples should be fine, as for now you install `simple_ai_server` and import `simple_ai`.

2023-04-07 00:36 UTC, Nintorac commented on src/simple_ai/models.py
> -        model_interface = model_interface.get("type", None)
sorry that was not clear at all 

so there's two things I was trying to say
1) slightly confusing variable naming, `model_interface = metadata.get(model_id).get("network", dict())` gives the network configuration for the server and is declared as `model_interface` then later `model_interface = model_interface.get("type", "gRPC")` model interface is redeclared this type from the type of the model interface

2) since `model_interface.get("type", None)`  will either return a string or None, this gets passed into `select_model_type(model_interface, task)`, model_interface if undeclared defaults to `gRPC` however it is never undeclared so the default is never used and all calls to this function without explicit type set in configuration will fail the first conditional of `select_model_type` and automatically fall back to the completion model

eg we hit the `f(None)` situation when type is not declared
```
>>> def f(a=0):
...     return a
... 
>>> print(f(), f(None), f(1))
0 None 1
```
Will print `0 None 1`

> everything is configured properly, neither the None or "gRPC" shall be accessed.

is this suggesting to make type required in the future?

2023-04-07 00:45 UTC, Nintorac commented on src/simple_ai/utils.py
>                  "role": "assistant",
ahh, yup, was too late at night for me on this one aha

2023-04-07 00:45 UTC, Nintorac commented on pyproject.toml
> +name = "simple_ai"
oh cool, didn't know it worked like that

2023-04-08 02:32 UTC, Nintorac commented
Any ideas on how to implement multiple servers running a single model? Would be keen to get complete and embeddings functional with a single backend model

2023-04-08 20:07 UTC, lhenault commented
Hey,

That should be pretty straightforward with a custom `serve` function, and adding the 2 servicers to the server / channel. There is an example of this [in the gRPC repository](https://github.com/grpc/grpc/blob/master/examples/python/multiplex/multiplex_server.py).

(I’m coming back to you shortly for the other thing we’ve been discussing, it’s a busy weekend :) )

2023-04-09 02:29 UTC, Nintorac commented
no worries :) thanks for the pointer!

2023-04-11 15:18 UTC, lhenault commented on src/simple_ai/models.py
> -        model_interface = model_interface.get("type", None)
Sorry I've been unclear too, but:

1. Agree on **1**, it's a bit ugly and confusing and should be changed.
2. Yes I am indeed leaning towards making `type` mandatory, as I believe it would avoid confusion (since I would like to at least add support for REST soon) with implicit values. That's actually already part of `models.toml.template`.

> 2\. automatically fall back to the completion model

Yes, there is room for improvement here. Wouldn't it be better to then raise an error / return `None` to avoid this, rather than burying default values in the middle of `get_model` in `model_interface = model_interface.get("type", "gRPC")`?

2023-04-11 17:39 UTC, lhenault commented
I have troubles building the Docker image, at last step, running `/bin/sh -c python3 get_models.py`:

```                                                                                                                                                                                                                                                                                                   
 > [11/11] RUN python3 get_models.py:
#15 1.504 No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
#15 1.504 Using /home/user/.cache/torch_extensions/py38_cu117 as PyTorch extensions root...
#15 1.504 Creating extension directory /home/user/.cache/torch_extensions/py38_cu117/wkv_cuda...
#15 1.504 Detected CUDA files, patching ldflags
#15 1.504 Emitting ninja build file /home/user/.cache/torch_extensions/py38_cu117/wkv_cuda/build.ninja...
#15 1.504 Traceback (most recent call last):
#15 1.504   File "get_models.py", line 2, in <module>
#15 1.504     from lib_raven import get_model
#15 1.504   File "/home/user/app/lib_raven.py", line 15, in <module>
#15 1.504     from rwkv.model import RWKV  # noqa: E402
#15 1.504   File "/home/user/.local/lib/python3.8/site-packages/rwkv/model.py", line 29, in <module>
#15 1.504     load(
#15 1.504   File "/home/user/.local/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1284, in load
#15 1.504     return _jit_compile(
#15 1.504   File "/home/user/.local/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1509, in _jit_compile
#15 1.504     _write_ninja_file_and_build_library(
#15 1.504   File "/home/user/.local/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1611, in _write_ninja_file_and_build_library
#15 1.504     _write_ninja_file_to_build_library(
#15 1.504   File "/home/user/.local/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 2007, in _write_ninja_file_to_build_library
#15 1.504     cuda_flags = common_cflags + COMMON_NVCC_FLAGS + _get_cuda_arch_flags()
#15 1.504   File "/home/user/.local/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1773, in _get_cuda_arch_flags
#15 1.504     arch_list[-1] += '+PTX'
#15 1.504 IndexError: list index out of range
------
executor failed running [/bin/sh -c python3 get_models.py]: exit code: 1
```

It seems to be related to CUDA. `docker` is a bit silly and cannot access GPU at build, I've ran into similar issues myself in the other examples. My suggestion here would be to:

- Move the download part from `get_model()` from `lib_raven.py` into a `download_models()` function in `get_models.py`, and only download the artefacts in it
- add `from get_models import download_models` in `lib_raven.py` and use this one inside `get_model`

This way `python3 get_models.py` would only gather the necesary files without any CUDA / GPU dependency.

2023-04-12 09:22 UTC, Nintorac commented
hmm you're right, thought I documented the workaround but looks like I left that out too!

FYI https://stackoverflow.com/questions/59008295/add-nvidia-runtime-to-docker-runtimes

it's a good clean up though to so have done as you suggest.

still trying to get the end to end to work though. the 3.9 is too high for the 3.8 of the image :(

2023-04-12 10:40 UTC, Nintorac commented
Ok, good to go, doesn't work end to end as a result of #17 but if that is fixed in main rebuilding the image without cache will then produce a working image

2023-04-12 12:08 UTC, lhenault commented
@Nintorac thanks for the change, will give it a try ASAP. There is a conflict in `src/simple_ai/server.py`

2023-04-19 11:33 UTC, cahya-wirawan commented
Any news with this PR? I would like to try it

2023-04-19 16:37 UTC, lhenault commented
> still trying to get the end to end to work though. the 3.9 is too high for the 3.8 of the image :(

I have a fix for this, which seemed to be the last thing to take care of, besides this I think we’re be good to go. Issue is impacting all the examples but it’s just a matter of changing a bit the `Dockerfile`.

Closing and merging by end of it shouldn’t be unrealistic @cahya-wirawan if that’s only this, I’ve just been a bit busy elsewhere lately. Thanks for your interest in this!

@Nintorac any thoughts here? That’s your contribution here after all :)

2023-04-19 22:18 UTC, Nintorac commented
Yea, its good to go if you don't use the Dockerfile.

I thought I had already pushed the Dockerfile fix tbh, just checked on my local and it's the broken one there. Will check on my GPU instance after work or rewrite it aha

2023-04-20 08:27 UTC, closed without merging